### ISSUE TITLE
Failed to activate the apathy-theme package

### ISSUE THREAD

**Issue by AdamDenoon** [coopermaruyama/apathy-theme#10]
I simply copied the Repo files into the github/apathy-theme folder, and live reloaded.

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.3
**Thrown From**: [apathy-theme](https://github.com/coopermaruyama/apathy-theme) package, v1.3.0
### Stack Trace

Failed to activate the apathy-theme package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/apple/github/apathy-theme/lib/apathy-view.coffee:2:7)
  at Object.<anonymous> (/Users/apple/github/apathy-theme/lib/apathy-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/apple/github/apathy-theme/lib/apathy.coffee:4:14)
  at Object.<anonymous> (/Users/apple/github/apathy-theme/lib/apathy.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at ThemePackage.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at ThemePackage.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:255:12)
  at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:234:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:48:26
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:43:12)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:361:50
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:557:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:459:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:466:24

```
### Commands

```
     -0:07.4.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "apathy-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
apathy-theme, v1.3.0

# Dev
No dev packages
```

**Comment by czxtm** [comment]
So you cloned the repo and are using the theme that way?

For atom 1.0 all views need to use space pen views, so you need to `cd` into the apathy-theme folder then run `apm install` which will install the dependency. I think since you cloned it from the repo, atom didn't install them for you. Let me know if that works.

**Comment by AdamDenoon** [comment]
I actually just restarted Atom, went to the Settings, took it off of the
theme, re-selected the theme, and it started working.

On Thu, May 28, 2015 at 4:07 PM, Cooper Maruyama notifications@github.com
wrote:

> So you cloned the repo and are using the theme that way?
> 
> For atom 1.0 all views need to use space pen views, so you need to cd
> into the apathy-theme folder then run apm install which will install the
> dependency. I think since you cloned it from the repo, atom didn't install
> them for you. Let me know if that works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/coopermaruyama/apathy-theme/issues/10#issuecomment-106599776
> .

##

**Comment by czxtm** [comment]
cool. And just to confirm, did you originally install the theme from the settings panel, or by cloning?
