### ISSUE TITLE
Using apathy growl info shows error

### ISSUE THREAD

**Issue by stebiger** [coopermaruyama/apathy-theme#14]
[Enter steps to reproduce below:]
1. installed theme on atom 1.0.2
2. restarted
3. chosen apathy syntax theme
4. crash error report in red appears 
5. copied error message here

**Atom Version**: 1.0.2
**System**: FOO123
**Thrown From**: [apathy-theme](https://github.com/coopermaruyama/apathy-theme) package, v1.5.1
### Stack Trace

Failed to activate the apathy-theme package

```
At Cannot read property 'cursors' of undefined

TypeError: Cannot read property 'cursors' of undefined
  at ApathyView.module.exports.ApathyView.getWordUnderCursor (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:278:35)
  at ApathyView.module.exports.ApathyView.decorateSemantic (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:243:31)
  at Text.<anonymous> (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:221:16)
  at Function.jQuery.extend.each (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\jquery\dist\jquery.js:374:23)
  at HTMLSpanElement.<anonymous> (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:209:9)
  at Function.jQuery.extend.each (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\jquery\dist\jquery.js:374:23)
  at [object Object].jQuery.fn.jQuery.each (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\jquery\dist\jquery.js:139:17)
  at ApathyView.module.exports.ApathyView.wrapTextNodes (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:207:26)
  at C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:53:8
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:276:9)
  at new ApathyView (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy-view.coffee:51:43)
  at Apathy.activate (C:\Users\xxx\.atom\packages\apathy-theme\lib\apathy.coffee:85:23)
  at ThemePackage.module.exports.Package.activateNow (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
  at C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\theme-package.js:48:26
  at ThemePackage.module.exports.Package.measure (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
  at ThemePackage.module.exports.ThemePackage.activate (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\theme-package.js:43:12)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\theme-manager.js:361:50
  at C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:557:16
  at C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:574:20
  at Emitter.module.exports.Emitter.emit (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:736:29)
  at Config.module.exports.Config.setRawValue (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:551:19)
  at Config.module.exports.Config.set (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:484:28)
  at C:\Users\xxx\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:491:24

```
### Commands

```
     -1:03.8.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "apathy-theme"
    ],
    "fileEncoding": "windows1252",
    "disabledPackages": [
      "auto-encoding",
      "autoflow"
    ]
  },
  "apathy-theme": {
    "altFont": "Inconsolata"
  }
}
```
### Installed Packages

``` coffee
# User
apathy-theme, v1.5.1
minimap, v4.11.2
open-recent, v2.3.0

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Fixed, please let me know if for some reason you're still seeing this error!

**Comment by stebiger** [comment]
Updated - not seeing the error anymore.
Thx for fast fix!
