### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/jonathan/.atom/packages/apathy-theme/lib/../styles/Inconsolata.less'

### ISSUE THREAD

**Issue by kung-foo** [coopermaruyama/apathy-theme#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.198.0
**System**: linux 4.0.0 
**Thrown From**: [apathy-theme](https://github.com/coopermaruyama/apathy-theme) package, v1.1.7
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/jonathan/.atom/packages/apathy-theme/lib/../styles/Inconsolata.less'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/home/jonathan/.atom/packages/apathy-theme/lib/../styles/Inconsolata.less'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Apathy.applyStylesheet (/home/jonathan/.atom/packages/apathy-theme/lib/apathy.coffee:109:28)
  at Apathy.doAltFont (/home/jonathan/.atom/packages/apathy-theme/lib/apathy.coffee:100:29)
  at /home/jonathan/.atom/packages/apathy-theme/lib/apathy.coffee:46:8
  at /usr/share/atom/resources/app.asar/src/config.js:557:16
  at /usr/share/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:190:28)
  at HTMLSelectElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:204:26)
  at HTMLSelectElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSelectElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
  2x -0:06.9.0 core:page-down (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "apathy-theme"
    ]
  },
  "apathy-theme": {
    "enableTreeViewStyles": true,
    "altFont": "Inconsolata"
  }
}
```
### Installed Packages

``` coffee
# User
apathy-theme, v1.1.7
autocomplete-plus, v2.13.1
file-icons, v1.5.5
go-plus, v3.3.10
linter, v0.12.2
linter-pep8, v0.1.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by kung-foo** [comment]
`ln -s ~/.atom/packages/apathy-theme/styles/inconsolata.less ~/.atom/packages/apathy-theme/styles/Inconsolata.less` fixes it

**Comment by czxtm** [comment]
Thanks for reporting this! 

Looks like somewhere along the way a typo broke the normalization of file names. This is now patched. Please confirm this issue is fixed.

**Comment by czxtm** [comment]
I'm closing this as it's been patched. If you're still seeing this issue please let me know.

**Comment by kung-foo** [comment]
Yep, works for me. Thanks!
