### ISSUE TITLE
Uncaught TypeError: Cannot read property 'linesComponent' of undefined

### ISSUE THREAD

**Issue by mohankv** [coopermaruyama/apathy-theme#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [apathy-theme](https://github.com/coopermaruyama/apathy-theme) package, v1.1.11
### Stack Trace

Uncaught TypeError: Cannot read property 'linesComponent' of undefined

```
At /Users/mkumar/.atom/packages/apathy-theme/lib/apathy.coffee:58

TypeError: Cannot read property 'linesComponent' of undefined
  at /Users/mkumar/.atom/packages/apathy-theme/lib/apathy.coffee:58:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1540:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:265:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:45:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:380:27)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:335:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:136:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:170:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:180:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:683:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1331:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1531:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1330:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:550:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```
### Commands

```
     -2:10.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:08.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:08.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:07.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 19x -2:00.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:49.4.0 key-binding-resolver:toggle (atom-text-editor.editor)
     -1:39.2.0 command-palette:toggle (div.settings-view.pane-item)
  2x -1:34.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:33.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:31.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:31.2.0 application:open-your-keymap (div.settings-view.pane-item)
     -0:42.3.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:17.7.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-apathy-theme.theme-one-dark-ui)
  8x -0:10.1.0 window:increase-font-size (atom-text-editor.editor.is-focused)
  5x -0:06.5.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "apathy-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
apathy-theme, v1.1.11

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Thanks for reporting this! Fixed by https://github.com/coopermaruyama/apathy-theme/commit/f74ccafc3bdd46b6062ab46a868ed7a01db035c9 please re-open if you get this error again.

**Comment by mohankv** [comment]
thank you!!
